# ’と'の違いに注意（１敗）

"""Typing practice sentences database."""

sentences = [
    [1, "Please submit the report by Friday.", "金曜日までに報告書を提出してください。"],
    [2, "The meeting starts at nine sharp.", "会議は9時ちょうどに始まります。"],
    [3, "Our flight was delayed due to weather.", "天候のため便が遅れました。"],
    [4, "She will attend the annual conference.", "彼女は年次会議に出席します。"],
    [5, "We appreciate your prompt response.", "迅速なご回答に感謝します。"],
    [6, "The invoice is attached for your reference.", "請求書を参照用に添付しました。"],
    [7, "Please review the contract before signing.", "署名前に契約書を確認してください。"],
    [8, "He was promoted to sales manager.", "彼は営業マネージャーに昇進しました。"],
    [9, "The factory will shut down for maintenance.", "工場は保守のため停止します。"],
    [10, "They negotiated a lower rental price.", "彼らは賃料の値下げを交渉しました。"],
    [11, "Customer feedback improved our product design.", "顧客の声で製品設計が改善しました。"],
    [12, "Please keep the receipt for reimbursement.", "精算のため領収書を保管してください。"],
    [13, "The shipment arrived earlier than expected.", "出荷は予定より早く到着しました。"],
    [14, "We apologize for any inconvenience caused.", "ご不便をおかけし申し訳ありません。"],
    [15, "I will follow up next week.", "来週フォローします。"],
    [16, "The printer is out of paper.", "プリンターの用紙が切れています。"],
    [17, "Let's schedule a call for tomorrow.", "明日の電話を予定しましょう。"],
    [18, "Please confirm your availability by noon.", "正午までに都合を確認してください。"],
    [19, "Our office will relocate in August.", "当社オフィスは8月に移転します。"],
    [20, "She is responsible for client relations.", "彼女は顧客対応を担当しています。"],
    [21, "The warranty expires in twelve months.", "保証は12か月で切れます。"],
    [22, "He requested an extension for the deadline.", "彼は締切延長を要請しました。"],
    [23, "Please ensure all fields are completed.", "全項目の記入をお願いします。"],
    [24, "They launched a new marketing campaign.", "新しいマーケティング施策を開始しました。"],
    [25, "Our profits increased despite rising costs.", "コスト上昇にもかかわらず利益が増えました。"],
    [26, "The agenda was shared in advance.", "議題は事前に共有されました。"],
    [27, "We need to finalize the budget.", "予算を確定する必要があります。"],
    [28, "Please proceed with the payment today.", "本日、支払いを進めてください。"],
    [29, "He will oversee the project timeline.", "彼がプロジェクトの工程を監督します。"],
    [30, "The software update fixed several bugs.", "ソフト更新で複数の不具合が修正されました。"],
    [31, "Could you resend the previous email?", "先ほどのメールを再送いただけますか。"],
    [32, "The cafeteria is closed on Mondays.", "食堂は月曜は休業です。"],
    [33, "She commutes to work by train.", "彼女は電車で通勤しています。"],
    [34, "Please bundle similar items together.", "類似の品目をまとめてください。"],
    [35, "They accepted the offer after negotiation.", "交渉後、彼らは提案を受け入れました。"],
    [36, "Our team exceeded the quarterly targets.", "私たちのチームは四半期目標を上回りました。"],
    [37, "Make sure the data is accurate.", "データが正確であることを確認してください。"],
    [38, "We are short-staffed this week.", "今週は人手が不足しています。"],
    [39, "Please submit expenses through the portal.", "経費はポータルから提出してください。"],
    [40, "The manager approved the travel request.", "マネージャーは出張申請を承認しました。"],
    [41, "I look forward to your reply.", "ご返信をお待ちしています。"],
    [42, "The package was damaged in transit.", "荷物は輸送中に破損しました。"],
    [43, "Please mute your microphone during presentations.", "発表中はマイクをミュートしてください。"],
    [44, "We will review your application shortly.", "申請を間もなく審査します。"],
    [45, "There is a discount for bulk orders.", "大量注文には割引があります。"],
    [46, "The seminar begins at ten thirty.", "セミナーは10時30分に始まります。"],
    [47, "He left for a business trip.", "彼は出張に出かけました。"],
    [48, "Please handle this matter discreetly.", "この件は内密に扱ってください。"],
    [49, "Our office hours have recently changed.", "営業時間が最近変更になりました。"],
    [50, "Could we postpone the meeting briefly?", "会議を少し延期できますか。"],
    [51, "The results will be announced tomorrow.", "結果は明日発表されます。"],
    [52, "She specializes in international trade law.", "彼女は国際商取引法を専門としています。"],
    [53, "The device is currently out of stock.", "その機器は現在在庫切れです。"],
    [54, "Please fill out the survey anonymously.", "アンケートは匿名でご記入ください。"],
    [55, "We need additional funding for expansion.", "拡大には追加資金が必要です。"],
    [56, "The proposal requires senior management approval.", "提案は上層部の承認が必要です。"],
    [57, "He is in charge of logistics.", "彼は物流担当です。"],
    [58, "Please double-check the attached spreadsheet.", "添付の表計算を再確認してください。"],
    [59, "Our branch will open next month.", "当支店は来月オープンします。"],
    [60, "They missed the deadline last Friday.", "彼らは先週金曜の締切に遅れました。"],
    [61, "We strive to exceed customer expectations.", "顧客の期待を超えるよう努めています。"],
    [62, "Please park only in designated areas.", "指定区域にのみ駐車してください。"],
    [63, "The contract is valid for two years.", "契約は2年間有効です。"],
    [64, "He apologized for the misunderstanding.", "彼は誤解を謝罪しました。"],
    [65, "Our system undergoes maintenance every weekend.", "当システムは毎週末に保守があります。"],
    [66, "Please attach receipts to your expense form.", "経費申請に領収書を添付してください。"],
    [67, "The keynote speaker canceled unexpectedly today.", "基調講演者が本日、突然キャンセルしました。"],
    [68, "We received several promising applications.", "有望な応募をいくつか受け取りました。"],
    [69, "Your membership will renew automatically.", "会員資格は自動更新されます。"],
    [70, "Please verify your identity at reception.", "受付で本人確認を行ってください。"],
    [71, "I will circulate the minutes later.", "後ほど議事録を回覧します。"],
    [72, "The new policy encourages flexible hours.", "新方針は柔軟な勤務時間を推奨します。"],
    [73, "He requested a refund for the ticket.", "彼はチケットの返金を求めました。"],
    [74, "Please back up your files regularly.", "ファイルを定期的にバックアップしてください。"],
    [75, "They offered a competitive compensation package.", "彼らは競争力のある待遇を提示しました。"],
    [76, "Our team collaborated across multiple departments.", "当チームは複数部門と連携しました。"],
    [77, "The venue can accommodate three hundred guests.", "会場は300名収容できます。"],
    [78, "Please restrict access to authorized personnel.", "権限者のみにアクセスを制限してください。"],
    [79, "We are launching a pilot program.", "パイロットプログラムを開始します。"],
    [80, "She submitted her resignation last week.", "彼女は先週、辞表を提出しました。"],
    [81, "The market outlook remains cautiously optimistic.", "市場見通しは慎重ながら楽観的です。"],
    [82, "Please clarify your primary requirements.", "主要な要件を明確にしてください。"],
    [83, "They are evaluating three potential vendors.", "彼らは3社の候補ベンダーを評価しています。"],
    [84, "The training session lasted two hours.", "研修は2時間続きました。"],
    [85, "We must comply with safety regulations.", "安全規則を順守しなければなりません。"],
    [86, "Please proceed to the security checkpoint.", "保安検査場にお進みください。"],
    [87, "He coordinates events for corporate clients.", "彼は法人向けイベントを調整しています。"],
    [88, "The deadline was extended by management.", "締切は経営陣により延長されました。"],
    [89, "Please submit a brief project summary.", "簡潔なプロジェクト概要を提出してください。"],
    [90, "We anticipate delays during peak season.", "繁忙期は遅延を見込んでいます。"],
    [91, "The supplier offered an additional discount.", "仕入先が追加割引を提示しました。"],
    [92, "Your order has been successfully processed.", "ご注文は正常に処理されました。"],
    [93, "Please sign in at the front desk.", "受付でサインインしてください。"],
    [94, "The brochure includes detailed product specifications.", "パンフレットには詳細仕様が含まれます。"],
    [95, "He is eligible for the scholarship.", "彼は奨学金の対象です。"],
    [96, "We will monitor performance indicators closely.", "指標を注意深く監視します。"],
    [97, "Please provide a revised cost estimate.", "改訂した見積を提示してください。"],
    [98, "The presentation slides were very informative.", "プレゼンのスライドはとても有益でした。"],
    [99, "Our team will conduct user interviews.", "当チームはユーザーインタビューを実施します。"],
    [100, "Please notify us of any changes.", "変更があればお知らせください。"],
]
